name: Freemchost Auto Renew Permanent

on:
  schedule:
    - cron: '10 3 * * *'
  workflow_dispatch: # 允许你在 GitHub 页面上手动点击按钮强制触发

  
jobs:
  browser-auto-renew:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装 Playwright 核心依赖
        run: |
          npm init -y
          npm install playwright

      - name: 初始化 谷歌环境
        run: npx playwright install chromium --with-deps

      - name: 执行自动化续期脚本
        env:
          FREE_EMAIL: ${{ secrets.FREE_EMAIL }}
          FREE_PASSWORD: ${{ secrets.FREE_PASSWORD }}
          SERVER_PAGE_URL: ${{ secrets.SERVER_PAGE_URL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}    # ← 新增
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}        # ← 新增
        run: node renew.js
        
      - name: 📥 上传失败现场截图
        if: failure() 
        uses: actions/upload-artifact@v4
        with:
          name: Error-Screenshot-Artifact
          path: screenshots/*.png
